source_list:
  - SB
  - OL
  - CP
  - ADDR

OL:
  sftp_conf:
    filetype: csv
    delimiter: |
    directory: /home/ubuntu/data

SB:
  mysql_conf:
    partition_column: App_Transaction_Id
    query: "(select * from testdb.transactionssync) as t"

s3_conf:
  s3_bucket: vamsibucket94
  staging_location: staging
ADDR:
  mongodb_config:
    database: school
    collection: students
CP:
  redshift_conf:
    filetype: csv
    delimiter: |
    dbtable: PUBLIC.TXN_FCT
    query: SELECT txn_id, create_time, amount, cust_id from PUBLIC.TXN_FCT


